### ISSUE TITLE
Add tab interface for the main content

### ISSUE THREAD

**Issue by Ustice** [Lesliemm78/resume-website#6]
When the user clicks on one of the menu items, it should show the relevant content in the main view

### Depends on

* #6

**Comment by Lesliemm78** [comment]
Note or self: onclick

**Comment by Lesliemm78** [comment]
OoO:
1. make each navbar element a button
2. link buttons to each section
3. buttons to "open" each section on click.
4. lots of reading. Off to the library, Batman!

**Comment by Lesliemm78** [comment]
jQuery is shorthand. It has a toggle command as well as hidden/show. Will use.
